### ISSUE TITLE
Minutes does not get added (fix in description)

### ISSUE THREAD

**Issue by Fedayk1n** [FeelZoR/Lighting-GameTime-Editor#1]
I am using the version 1.4, but the addminutes does not function properly, the way to fix this is go to 
line 526 and replace that part with

Time.prototype.addMinute = function(minutes) {
    this.minute += Number(minutes);
    if (this.minute >= 60) {
		this.minute -= Number(60) //incase the player adds quite a number of minutes.
        this.addHour();
    }
}

**Comment by FeelZoR** [comment]
Thanks for the report !
I couldn't work on the plugin for the last few days because of exams, but now I'm back and it seems the issue has been fixed !

Do not hesitate to open another issue if you encounter any other problem with the plugin ^^

**Comment by Fedayk1n** [comment]
You're welcome.
